name: Run flake8 & pytest

on:
  push:

jobs:
  CI:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run flake8 and pytest
        run: |
          flake8 .
          pytest -s