name: Run flake8 & pytest

on:
  push:

jobs:
  CI:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run flake8 and pytest
        run: |
          pip install -r requirements.txt
          flake8 .
          pytest -s

      - uses: actions/checkout@v3
      - name: Update README.md
        run: |
          git config --global user.email "1phanatasmas@korea.ac.kr"
          git config --global user.name "1pha"

          # Check if there are changes0
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add README.md
            git commit -m "<Action> auto update README.md"
            git push origin main
          fi